Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,214 +1,115 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-################################################################################
-# Essentials
-################################################################################
+# fail fast
+set -e
 
-set -x
+# debug
+# set -x
 
-HEROKU_BUILD_DIR="$1"
-HEROKU_CACHE_DIR="$2"
-HEROKU_ENV_DIR="$3"
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-HEROKU_THIS_DIR=$(dirname "$0")
-HEROKU_PACK_DIR=$(
-    # shellcheck disable=SC2164
-    cd "$HEROKU_THIS_DIR"
-    cd ..
-    pwd
-)
-
-# Essental functions
-
-echo_extra() {
-    echo "-----> $*" | indent
+function error() {
+  echo " !     $*" >&2
+  exit 1
 }
 
-export_env_vars() {
-    env_dir=$1
-    whitelist_regex=${2:-''}
-    blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
-
-    if [ -d "$env_dir" ]; then
-        # shellcheck disable=SC2045
-        for e in $(ls "$env_dir"); do
-            # shellcheck disable=SC2086
-            echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" && export "$e=$(cat $env_dir/$e)"
-            :
-        done
-    fi
+function topic() {
+  echo "-----> $*"
 }
 
-indent() {
-    sed -u 's/^/      /'
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
 }
 
-# Load env variables
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
+cp -a binaries-$STACK/* "$CACHE_DIR/apt/sources"
+APT_SOURCELIST_DIR="$CACHE_DIR/apt/sources"   # place custom sources.list here
 
-export_env_vars "$HEROKU_ENV_DIR"
+APT_SOURCES="$APT_SOURCELIST_DIR/sources.list"
 
-################################################################################
-# Variables
-################################################################################
+APT_VERSION=$(apt-get -v | awk 'NR == 1{ print $2 }')
 
-TOR_COMMAND="run_tor_proxy"
-TOR_CONFIG_FILE="${HOME}/tor/etc/tor/torrc"
-TOR_DIST_URL="https://dist.torproject.org/"
+case "$APT_VERSION" in
+  0* | 1.0*) APT_FORCE_YES="--force-yes";;
+  *)         APT_FORCE_YES="--allow-downgrades --allow-remove-essential --allow-change-held-packages";;
+esac
 
-if [ -z "$TOR_VERSION" ]; then
-    TOR_SRCH=".\..\..\..\.tar"
-    TOR_PACKAGE=$(curl -s "$TOR_DIST_URL" | grep -o -e "$TOR_SRCH" | sort | tail -1)
-    TOR_VERSION="${TOR_PACKAGE/.tar/}"
-fi
-
-TOR_SRC_NAME="tor-${TOR_VERSION}.tar.gz"
-
-if [ -z "$TOR_PROXY_PORT" ]; then
-    TOR_PROXY_PORT="9050"
-fi
-
-if [ -z "$TOR_CONTROL_PORT" ]; then
-    TOR_CONTROL_PORT="9051"
-fi
-
-if [ -z "$TOR_CONTROL_PASS" ]; then
-    TOR_CONTROL_PASS="torProxy@123"
-fi
-
-TOR_SIG_NAME=${TOR_SRC_NAME}.asc
-TOR_SRC_URL=${TOR_DIST_URL}${TOR_SRC_NAME}
-TOR_SRC_SIG_URL=${TOR_DIST_URL}${TOR_SIG_NAME}
-
-################################################################################
-# Check Cache
-################################################################################
-
-mkdir -p "$HEROKU_CACHE_DIR"
-grep -wq "${TOR_SRC_NAME}" "${HEROKU_CACHE_DIR}/tor_version.txt"
-
-# shellcheck disable=SC2181
-if [ $? -eq 0 ]; then
-    IS_TOR_CACHED=1
+if [ -f $APT_CACHE_DIR/Aptfile ] && cmp -s $BUILD_DIR/Aptfile $APT_CACHE_DIR/Aptfile ; then
+  # Old Aptfile is the same as new
+  topic "Reusing cache"
 else
-    IS_TOR_CACHED=0
+  # Aptfile changed or does not exist
+  topic "Detected Aptfile changes, flushing cache"
+  rm -rf $APT_CACHE_DIR
+  mkdir -p "$APT_CACHE_DIR/archives/partial"
+  mkdir -p "$APT_STATE_DIR/lists/partial"
+  mkdir -p "$APT_SOURCELIST_DIR"   # make dir for sources
+  cp -f "$BUILD_DIR/Aptfile" "$APT_CACHE_DIR/Aptfile"
+  cat "/etc/apt/sources.list" > "$APT_SOURCES"    # no cp here
+  # add custom repositories from Aptfile to sources.list
+  # like>>    :repo:deb http://cz.archive.ubuntu.com/ubuntu artful main universe
+  topic "Adding custom repositories"
+  cat $BUILD_DIR/Aptfile | grep -s -e "^:repo:" | sed 's/^:repo:\(.*\)\s*$/\1/g' >> $APT_SOURCES
 fi
 
-################################################################################
-# Download Tor
-################################################################################
+APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
+# Override the use of /etc/apt/sources.list (sourcelist) and /etc/apt/sources.list.d/* (sourceparts).
+APT_OPTIONS="$APT_OPTIONS -o dir::etc::sourcelist=$APT_SOURCES -o dir::etc::sourceparts=/dev/null"
 
-if [ $IS_TOR_CACHED -eq 0 ]; then
-    echo "Downloading ${TOR_SRC_URL}"
-    wget -q "$TOR_SRC_URL"
+topic "Updating apt caches"
+apt-get $APT_OPTIONS update | indent
 
-    # shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
-        echo_extra "FAILED to obtain ${TOR_SRC_URL}"
-        exit 1
-    fi
+for PACKAGE in $(cat $BUILD_DIR/Aptfile | grep -v -s -e '^#' | grep -v -s -e "^:repo:"); do
+  if [[ $PACKAGE == *deb ]]; then
+    PACKAGE_NAME=$(basename $PACKAGE .deb)
+    PACKAGE_FILE=$APT_CACHE_DIR/archives/$PACKAGE_NAME.deb
 
-    echo "Downloading ${TOR_SRC_SIG_URL}"
-    wget -q "$TOR_SRC_SIG_URL"
+    topic "Fetching $PACKAGE"
+    curl -s -L -z $PACKAGE_FILE -o $PACKAGE_FILE $PACKAGE 2>&1 | indent
+  else
+    topic "Fetching .debs for $PACKAGE"
+    apt-get $APT_OPTIONS -y $APT_FORCE_YES -d install --reinstall $PACKAGE | indent
+  fi
+done
 
-    # shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
-        echo_extra "FAILED to obtain signature ${TOR_SRC_SIG_URL}"
-        exit 1
-    fi
-fi
+mkdir -p $BUILD_DIR/.apt
 
-################################################################################
-# Check Integrity
-################################################################################
+for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
+  topic "Installing $(basename $DEB)"
+  dpkg -x $DEB $BUILD_DIR/.apt/
+done
 
-if [ $IS_TOR_CACHED -eq 0 ]; then
-    gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290
-    gpg --keyserver pool.sks-keyservers.net --recv-keys 0x6AFEE6D49E92B601
-    gpg --verify "$TOR_SIG_NAME" "$TOR_SRC_NAME" | grep -c "Good signature"
-
-    if [ $? -lt 1 ]; then
-        echo_extra "FAILED to verify the signature"
-        exit 1
-    fi
-fi
-
-################################################################################
-# Compile Tor
-################################################################################
-
-if [ $IS_TOR_CACHED -eq 0 ]; then
-    tar -zxf "$TOR_SRC_NAME"
-    cd "tor-${TOR_VERSION}" || echo "FAILED to configure Tor"
-
-    ./configure --prefix="${HEROKU_CACHE_DIR}/tor"
-    # shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
-        echo_extra "FAILED to configure for compiling Tor"
-        exit 1
-    fi
-
-    make install
-    # shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
-        echo_extra "FAILED to compile Tor"
-        exit 1
-    fi
-fi
-
-################################################################################
-# Install Tor
-################################################################################
-
-# Get the build from the cache
-cp -r "${HEROKU_CACHE_DIR}/tor" "$HEROKU_BUILD_DIR"
-
-# Save the version compiled now
-echo "$TOR_SRC_NAME" >"${HEROKU_CACHE_DIR}/tor_version.txt"
-
-################################################################################
-# Configure Tor
-################################################################################
-
-echo_extra "Configuring Tor Proxy"
-
-TOR_HASHED_PASS=$("${HEROKU_BUILD_DIR}/tor/bin/tor" --hash-password "$TOR_CONTROL_PASS")
-
-if [ -n "$TOR_CONF_FILE_URL" ]; then
-    wget "$TOR_CONF_FILE_URL" -O "${HEROKU_BUILD_DIR}/tor/etc/tor/torrc_custom"
-
-    TOR_CONFIG_FILE="${TOR_CONFIG_FILE}_custom"
-fi
-
-cat >>"${HEROKU_BUILD_DIR}/tor/bin/${TOR_COMMAND}" <<EOF
-#!/usr/bin/env bash
-echo "Writing the configuration file"
-if ! grep -q "SOCKSPort ${TOR_PROXY_PORT}" ${TOR_CONFIG_FILE}; then
-  echo "SOCKSPort ${TOR_PROXY_PORT}" >> ${TOR_CONFIG_FILE}
-fi
-if ! grep -q "ControlPort ${TOR_CONTROL_PORT}" ${TOR_CONFIG_FILE}; then
-  echo "ControlPort ${TOR_CONTROL_PORT}" >> ${TOR_CONFIG_FILE}
-fi
-if ! grep -q "HashedControlPassword ${TOR_HASHED_PASS}" ${TOR_CONFIG_FILE}; then
-  echo "HashedControlPassword ${TOR_HASHED_PASS}" >> ${TOR_CONFIG_FILE}
-fi
-echo "Launching the program: Tor Proxy"
-"${HOME}/tor/bin/tor" -f ${TOR_CONFIG_FILE} &
-exec \$*
+topic "Writing profile script"
+mkdir -p $BUILD_DIR/.profile.d
+cat <<EOF >$BUILD_DIR/.profile.d/000_apt.sh
+export PATH="\$HOME/.apt/usr/bin:\$PATH"
+export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/.apt/usr/include:\$HOME/.apt/usr/include/x86_64-linux-gnu:\$INCLUDE_PATH"
+export CPATH="\$INCLUDE_PATH"
+export CPPPATH="\$INCLUDE_PATH"
+export PKG_CONFIG_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/i386-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/pkgconfig:\$PKG_CONFIG_PATH"
 EOF
 
-chmod a+x "${HEROKU_BUILD_DIR}/tor/bin/${TOR_COMMAND}"
+export PATH="$BUILD_DIR/.apt/usr/bin:$PATH"
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LD_LIBRARY_PATH"
+export LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LIBRARY_PATH"
+export INCLUDE_PATH="$BUILD_DIR/.apt/usr/include:$BUILD_DIR/.apt/usr/include/x86_64-linux-gnu:$INCLUDE_PATH"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+export PKG_CONFIG_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
 
-################################################################################
-# Activate Runner
-################################################################################
+#give environment to later buildpacks
+export | grep -E -e ' (PATH|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  > "$LP_DIR/export"
 
-echo_extra "Activating the auto-runner"
-
-if [ ! -d "${HEROKU_BUILD_DIR}/.profile.d/" ]; then
-    mkdir "${HEROKU_BUILD_DIR}/.profile.d/"
-fi
-
-cp "${HEROKU_PACK_DIR}/extra/${TOR_COMMAND}.sh" "${HEROKU_BUILD_DIR}/.profile.d/"
-chmod +x "${HEROKU_BUILD_DIR}/.profile.d/${TOR_COMMAND}.sh"
-
-echo_extra "SUCCESS at installing Tor Proxy"
+topic "Rewrite package-config files"
+find $BUILD_DIR/.apt -type f -ipath '*/pkgconfig/*.pc' | xargs --no-run-if-empty -n 1 sed -i -e 's!^prefix=\(.*\)$!prefix='"$BUILD_DIR"'/.apt\1!g'
