Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,28 +6,41 @@
 
 set -x
 
-HEROKU_BUILD_DIR=$1
-HEROKU_CACHE_DIR=$2
-HEROKU_ENV_DIR=$3
+HEROKU_BUILD_DIR="$1"
+HEROKU_CACHE_DIR="$2"
+HEROKU_ENV_DIR="$3"
+
+HEROKU_THIS_DIR=$(dirname "$0")
+HEROKU_PACK_DIR=$(
+    # shellcheck disable=SC2164
+    cd "$HEROKU_THIS_DIR"
+    cd ..
+    pwd
+)
 
 # Essental functions
 
-export_env_dir() {
-  env_dir=$1
-  whitelist_regex=${2:-''}
-  blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
-  if [ -d "$env_dir" ]; then
-    for e in $(ls $env_dir); do
-      echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" &&
-      export "$e=$(cat $env_dir/$e)"
-      echo "$e=$(cat $env_dir/$e)"
-      :
-    done
-  fi
+echo_extra() {
+    echo "-----> $*" | indent
+}
+
+export_env_vars() {
+    env_dir=$1
+    whitelist_regex=${2:-''}
+    blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
+
+    if [ -d "$env_dir" ]; then
+        # shellcheck disable=SC2045
+        for e in $(ls "$env_dir"); do
+            # shellcheck disable=SC2086
+            echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" && export "$e=$(cat $env_dir/$e)"
+            :
+        done
+    fi
 }
 
 indent() {
-  sed -u 's/^/      /'
+    sed -u 's/^/      /'
 }
 
 # Load env variables
@@ -39,21 +52,27 @@ export_env_vars "$HEROKU_ENV_DIR"
 ################################################################################
 
 TOR_COMMAND="run_tor_proxy"
+TOR_CONFIG_FILE="${HOME}/tor/etc/tor/torrc"
 TOR_DIST_URL="https://dist.torproject.org/"
 
 if [ -z "$TOR_VERSION" ]; then
-  TOR_SRC_NAME=tor-${TOR_VERSION}.tar.gz
-else
-  TOR_SRCH="tor-.\..\..\..\.tar\.gz"
-  TOR_SRC_NAME=$(curl -s "$TOR_DIST_URL" | grep -o -e "$TOR_SRCH" | sort | tail -1)
+    TOR_SRCH=".\..\..\..\.tar"
+    TOR_PACKAGE=$(curl -s "$TOR_DIST_URL" | grep -o -e "$TOR_SRCH" | sort | tail -1)
+    TOR_VERSION="${TOR_PACKAGE/.tar/}"
 fi
 
-if [ -z "$TOR_CONTROL_PASS" ]; then
-  TOR_CONTROL_PASS="torProxy@123"
+TOR_SRC_NAME="tor-${TOR_VERSION}.tar.gz"
+
+if [ -z "$TOR_PROXY_PORT" ]; then
+    TOR_PROXY_PORT="9050"
 fi
 
 if [ -z "$TOR_CONTROL_PORT" ]; then
-  TOR_CONTROL_PORT="9051"
+    TOR_CONTROL_PORT="9051"
+fi
+
+if [ -z "$TOR_CONTROL_PASS" ]; then
+    TOR_CONTROL_PASS="torProxy@123"
 fi
 
 TOR_SIG_NAME=${TOR_SRC_NAME}.asc
@@ -67,10 +86,11 @@ TOR_SRC_SIG_URL=${TOR_DIST_URL}${TOR_SIG_NAME}
 mkdir -p "$HEROKU_CACHE_DIR"
 grep -wq "${TOR_SRC_NAME}" "${HEROKU_CACHE_DIR}/tor_version.txt"
 
+# shellcheck disable=SC2181
 if [ $? -eq 0 ]; then
-   IS_TOR_CACHED=1
+    IS_TOR_CACHED=1
 else
-   IS_TOR_CACHED=0
+    IS_TOR_CACHED=0
 fi
 
 ################################################################################
@@ -81,16 +101,18 @@ if [ $IS_TOR_CACHED -eq 0 ]; then
     echo "Downloading ${TOR_SRC_URL}"
     wget -q "$TOR_SRC_URL"
 
+    # shellcheck disable=SC2181
     if [ $? -ne 0 ]; then
-        echo "FAILED to obtain ${TOR_SRC_URL}" | indent
+        echo_extra "FAILED to obtain ${TOR_SRC_URL}"
         exit 1
     fi
 
     echo "Downloading ${TOR_SRC_SIG_URL}"
     wget -q "$TOR_SRC_SIG_URL"
 
+    # shellcheck disable=SC2181
     if [ $? -ne 0 ]; then
-        echo "FAILED to obtain signature ${TOR_SRC_SIG_URL}" | indent
+        echo_extra "FAILED to obtain signature ${TOR_SRC_SIG_URL}"
         exit 1
     fi
 fi
@@ -98,13 +120,14 @@ fi
 ################################################################################
 # Check Integrity
 ################################################################################
-if [ $IS_TOR_CACHED -eq 0 ] ; then
+
+if [ $IS_TOR_CACHED -eq 0 ]; then
     gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290
     gpg --keyserver pool.sks-keyservers.net --recv-keys 0x6AFEE6D49E92B601
     gpg --verify "$TOR_SIG_NAME" "$TOR_SRC_NAME" | grep -c "Good signature"
 
     if [ $? -lt 1 ]; then
-        echo "FAILED to verify the signature" | indent
+        echo_extra "FAILED to verify the signature"
         exit 1
     fi
 fi
@@ -112,20 +135,23 @@ fi
 ################################################################################
 # Compile Tor
 ################################################################################
-if [ $IS_TOR_CACHED -eq 0 ] ; then
+
+if [ $IS_TOR_CACHED -eq 0 ]; then
     tar -zxf "$TOR_SRC_NAME"
-    cd "tor-${TOR_VER}" || echo "FAILED to configure Tor"
+    cd "tor-${TOR_VERSION}" || echo "FAILED to configure Tor"
 
     ./configure --prefix="${HEROKU_CACHE_DIR}/tor"
+    # shellcheck disable=SC2181
     if [ $? -ne 0 ]; then
-        echo "FAILED to configure for compiling Tor" | indent
+        echo_extra "FAILED to configure for compiling Tor"
         exit 1
     fi
 
     make install
+    # shellcheck disable=SC2181
     if [ $? -ne 0 ]; then
-        echo "FAILED to compile Tor" | indent
-        exit  1
+        echo_extra "FAILED to compile Tor"
+        exit 1
     fi
 fi
 
@@ -137,30 +163,52 @@ fi
 cp -r "${HEROKU_CACHE_DIR}/tor" "$HEROKU_BUILD_DIR"
 
 # Save the version compiled now
-echo "$TOR_SRC_NAME" > "${HEROKU_CACHE_DIR}/tor_version.txt"
+echo "$TOR_SRC_NAME" >"${HEROKU_CACHE_DIR}/tor_version.txt"
 
-echo "Configuring the Tor Proxy" | indent
+################################################################################
+# Configure Tor
+################################################################################
+
+echo_extra "Configuring Tor Proxy"
 
 TOR_HASHED_PASS=$("${HEROKU_BUILD_DIR}/tor/bin/tor" --hash-password "$TOR_CONTROL_PASS")
 
-cat > "${HEROKU_BUILD_DIR}/tor/bin/${TOR_COMMAND}" <<EOF
+if [ -n "$TOR_CONF_FILE_URL" ]; then
+    wget "$TOR_CONF_FILE_URL" -O "${HEROKU_BUILD_DIR}/tor/etc/tor/torrc_custom"
+
+    TOR_CONFIG_FILE="${TOR_CONFIG_FILE}_custom"
+fi
+
+cat >>"${HEROKU_BUILD_DIR}/tor/bin/${TOR_COMMAND}" <<EOF
 #!/usr/bin/env bash
-
-echo "Setting up the control server"
-
-echo "SocksPort 0.0.0.0:9050" > $HOME/tor/etc/tor/torrc
-echo "ControlPort 9051" > $HOME/tor/etc/tor/torrc
-echo "CookieAuthentication 0" >> $HOME/tor/etc/tor/torrc
-
-"${HOME}/tor/bin/tor" -f "${HOME}/tor/etc/tor/torrc" &
+echo "Writing the configuration file"
+if ! grep -q "SOCKSPort ${TOR_PROXY_PORT}" ${TOR_CONFIG_FILE}; then
+  echo "SOCKSPort ${TOR_PROXY_PORT}" >> ${TOR_CONFIG_FILE}
+fi
+if ! grep -q "ControlPort ${TOR_CONTROL_PORT}" ${TOR_CONFIG_FILE}; then
+  echo "ControlPort ${TOR_CONTROL_PORT}" >> ${TOR_CONFIG_FILE}
+fi
+if ! grep -q "HashedControlPassword ${TOR_HASHED_PASS}" ${TOR_CONFIG_FILE}; then
+  echo "HashedControlPassword ${TOR_HASHED_PASS}" >> ${TOR_CONFIG_FILE}
+fi
+echo "Launching the program: Tor Proxy"
+"${HOME}/tor/bin/tor" -f ${TOR_CONFIG_FILE} &
 exec \$*
 EOF
 
 chmod a+x "${HEROKU_BUILD_DIR}/tor/bin/${TOR_COMMAND}"
 
-echo "Activating the auto-runner" | indent
+################################################################################
+# Activate Runner
+################################################################################
 
-cp "${BUILDPACK_DIR}/extra/${TOR_COMMAND}.sh" "${BUILD_DIR}/.profile.d/"
-chmod +x "${BUILD_DIR}/.profile.d/${TOR_COMMAND}.sh"
+echo_extra "Activating the auto-runner"
 
-echo "SUCCESS at installing Tor Proxy" | indent
+if [ ! -d "${HEROKU_BUILD_DIR}/.profile.d/" ]; then
+    mkdir "${HEROKU_BUILD_DIR}/.profile.d/"
+fi
+
+cp "${HEROKU_PACK_DIR}/extra/${TOR_COMMAND}.sh" "${HEROKU_BUILD_DIR}/.profile.d/"
+chmod +x "${HEROKU_BUILD_DIR}/.profile.d/${TOR_COMMAND}.sh"
+
+echo_extra "SUCCESS at installing Tor Proxy"
